"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
import sys
from decouple import AutoConfig, Config, RepositoryEnv
from datetime import timedelta
from urllib.parse import urlparse
import ipaddress
import logging


def _split_csv(value, default=''):
    raw = value if value is not None else default
    return [item.strip() for item in str(raw).split(',') if item.strip()]


def _normalize_origin(value: str) -> str:
    origin = (value or '').strip().rstrip('/')
    if not origin:
        return ''
    if origin.startswith('http://') or origin.startswith('https://'):
        return origin
    return f'https://{origin}'


def _append_unique(items: list[str], value: str):
    if value and value not in items:
        items.append(value)


logger = logging.getLogger(__name__)
IS_TEST_RUN = any(arg in {'test', 'pytest'} for arg in sys.argv)


def _parse_ip_network_pool(raw_value: str) -> tuple:
    """
    Поддерживает и отдельные IP, и CIDR:
    77.75.156.11,185.71.76.0/27,2a02:5180::/32
    """
    pool = []
    for item in _split_csv(raw_value, default=''):
        try:
            # strict=False позволяет передавать и "голый" IP.
            pool.append(ipaddress.ip_network(item, strict=False))
        except ValueError:
            logger.warning("Некорректный IP/CIDR в YOOKASSA_WEBHOOK_ALLOWED_IPS: %s", item)
    return tuple(pool)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Явно выбираем env-файл backend, чтобы не ловить конфликты с корневым/.frontend env.
_explicit_env_path = os.getenv('DJANGO_ENV_FILE', '').strip()
if _explicit_env_path:
    _cfg = Config(RepositoryEnv(_explicit_env_path))
else:
    default_backend_env = BASE_DIR / '.env'
    _cfg = Config(RepositoryEnv(str(default_backend_env))) if default_backend_env.exists() else AutoConfig(search_path=str(BASE_DIR))


def config(name, default=None, cast=None):
    kwargs = {}
    if default is not None:
        kwargs['default'] = default
    if cast is not None:
        kwargs['cast'] = cast
    return _cfg(name, **kwargs)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = _split_csv(
    config(
        'ALLOWED_HOSTS',
        default='127.0.0.1,localhost,backend',
    )
)

DEV_NGROK_URL = config('DEV_NGROK_URL', default='')
_ngrok_origin = _normalize_origin(DEV_NGROK_URL)
if _ngrok_origin:
    _ngrok_host = urlparse(_ngrok_origin).hostname
    if _ngrok_host and _ngrok_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_ngrok_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'users',
    'catalog',
    'cart',
    'orders',
    'reviews',
    'payments',
]


FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
YOOKASSA_RETURN_URL = config('YOOKASSA_RETURN_URL', default=f'{FRONTEND_URL.rstrip("/")}/checkout/success')
YOOKASSA_ACCOUNT_ID = config('YOOKASSA_ACCOUNT_ID', default='')
YOOKASSA_SECRET_KEY = config('YOOKASSA_SECRET_KEY', default='')
YOOKASSA_RECEIPT_VAT_CODE = config('YOOKASSA_RECEIPT_VAT_CODE', default='1')
YOOKASSA_RECEIPT_PAYMENT_MODE = config('YOOKASSA_RECEIPT_PAYMENT_MODE', default='full_payment')
YOOKASSA_RECEIPT_PAYMENT_SUBJECT = config('YOOKASSA_RECEIPT_PAYMENT_SUBJECT', default='commodity')
YOOKASSA_RECEIPT_MEASURE = config('YOOKASSA_RECEIPT_MEASURE', default='piece')
YOOKASSA_WEBHOOK_ALLOWED_IPS = _parse_ip_network_pool(
    config('YOOKASSA_WEBHOOK_ALLOWED_IPS', default='')
)
YOOKASSA_WEBHOOK_TRUST_X_FORWARDED_FOR = config(
    'YOOKASSA_WEBHOOK_TRUST_X_FORWARDED_FOR',
    default=False,
    cast=bool,
)
YOOKASSA_WEBHOOK_ENFORCE_IP_WHITELIST = config(
    'YOOKASSA_WEBHOOK_ENFORCE_IP_WHITELIST',
    default=(not DEBUG),
    cast=bool,
)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@lkmshop.local')
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
FEEDBACK_TO_EMAIL = config('FEEDBACK_TO_EMAIL', default=(EMAIL_HOST_USER or DEFAULT_FROM_EMAIL))

REFRESH_COOKIE_SECURE = config('REFRESH_COOKIE_SECURE', default=not DEBUG, cast=bool)
REFRESH_COOKIE_SAMESITE = config('REFRESH_COOKIE_SAMESITE', default='Lax')
REFRESH_COOKIE_PATH = config('REFRESH_COOKIE_PATH', default='/')

# Ссылка на сброс пароля действует 1 час.
PASSWORD_RESET_TIMEOUT = config('PASSWORD_RESET_TIMEOUT', default=3600, cast=int)
EMAIL_VERIFICATION_CODE_TTL = config('EMAIL_VERIFICATION_CODE_TTL', default=600, cast=int)
EMAIL_VERIFICATION_RESEND_COOLDOWN = config('EMAIL_VERIFICATION_RESEND_COOLDOWN', default=60, cast=int)
EMAIL_VERIFICATION_MAX_ATTEMPTS = config('EMAIL_VERIFICATION_MAX_ATTEMPTS', default=5, cast=int)
EMAIL_VERIFICATION_PENDING_RETENTION = config('EMAIL_VERIFICATION_PENDING_RETENTION', default=86400, cast=int)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
CSRF_TRUSTED_ORIGINS = _split_csv(
    config(
        'CSRF_TRUSTED_ORIGINS',
        default='http://localhost:3000,http://127.0.0.1:3000',
    )
)
_append_unique(CSRF_TRUSTED_ORIGINS, _ngrok_origin)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5544'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = _split_csv(
    config(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:3000,http://127.0.0.1:3000',
    )
)
_append_unique(CORS_ALLOWED_ORIGINS, _ngrok_origin)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': config('THROTTLE_AUTH_LOGIN_RATE', default='5/min'),
        'auth_refresh': config('THROTTLE_AUTH_REFRESH_RATE', default='120/hour'),
        'auth_password_reset_request': config('THROTTLE_AUTH_PASSWORD_RESET_REQUEST_RATE', default='3/hour'),
        'auth_password_reset_validate': config('THROTTLE_AUTH_PASSWORD_RESET_VALIDATE_RATE', default='20/hour'),
        'auth_password_reset_confirm': config('THROTTLE_AUTH_PASSWORD_RESET_CONFIRM_RATE', default='10/hour'),
        'auth_register_request_code': config('THROTTLE_AUTH_REGISTER_REQUEST_CODE_RATE', default='3/hour'),
        'auth_register_confirm_code': config('THROTTLE_AUTH_REGISTER_CONFIRM_CODE_RATE', default='15/hour'),
        'feedback_send': config('THROTTLE_FEEDBACK_SEND_RATE', default='3/hour'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_MINUTES', default=30, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_DAYS', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

if IS_TEST_RUN:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    }
