services:
  db:
    image: postgres:17
    container_name: lkm_shop_db
    env_file:
      - ./database/.env
    ports:
      - "${DB_EXTERNAL_PORT:-5544}:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: lkm_shop_backend
    working_dir: /app/backend
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONUNBUFFERED: "1"
      DJANGO_ENV_FILE: /app/backend/.env
      DB_HOST: db
      DB_PORT: "5432"
    command: ["sh", "/app/backend/entrypoint.sh"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "${BACKEND_EXTERNAL_PORT:-8080}:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: lkm_shop_frontend
    working_dir: /app/frontend
    env_file:
      - ./frontend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "${FRONTEND_EXTERNAL_PORT:-3000}:3000"
    depends_on:
      - backend
    restart: unless-stopped
