services:
  lkmShopDataBase:
    image: postgres:latest
    container_name: lkmShopDataBase
    env_file:
      - ./.env
    ports:
      - "${DB_EXTERNAL_PORT:-5544}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - shop_network
networks:
  shop_network:
    driver: bridge
