services:
  lkmShopDataBase:
    image: postgres:latest
    container_name: lkmShopDataBase
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5544:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - shop_network
networks:
  shop_network:
    driver: bridge
